### ISSUE TITLE
Research: Investigate octavia w/ proxy protocol options

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#250] opened 2023-01-17 22:28 UTC
As a container cluster users (DevOps team), I want to use externalTrafficPolicy: local behind a Load-Balancer not only for better performance, but to be able to see the Client IP address in e.g. the ingress controller.
In our current reference implementation, this is not the case, as the internal IP of the load-balancer (octavia) will be seen by the service, not the real client IP.

When we use the nginx-ingress, there should be a possibility to create a work around:
- octavia can be told to use the proxy protocol to communicate the real client IP to a service
- the service -- in this case nginx -- can be told to evaluate the special header

As this does need service specific configuration for most services (some *might* auto-detect and -evaluate a prozy protocol header), this is unfortunately not a generic solution. But still useful: As we offer to create an nginx-ingress along with cluster deployment, we can set everything in octavia and in ingress from one place to make it work. Further services that the user adds manually however, will not have client-IPs out-of-the-box unfortunately. Still useful ...

This user story is about researching whether this will work and how to make it work in our SCS reference implementation.
It is a reaction to the discussion in issue #227.

**Comment by garloff** [comment] 2023-01-17 22:43
Prior discussion on using the proxy protocol in the nginx-ingress-octavia situation in our reference implementation:
https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/184
Please read carefully. (Here's a TL;DR anyway:)
- We know how to patch the nginx deployment files to enable the openstack annotation to use proxy headers.
- We also can tell nginx to expect proxy headers, but this breaks internal connections, as noted by @flyersa 
- There may be a way to restrict proxy-protocol usage, but this needs research & validation.

**Comment by garloff** [comment] 2023-01-17 22:45
Your insight is very welcome, @batistein , @janiskemper , @joshmue , @chess-knight , @ajfriesen, @horazont .

**Comment by chess-knight** [comment] 2023-01-18 09:12
I tested the behaviour of `externalTrafficPolicy` and the proxy protocol on the Hetzner Cloud so I am sharing notes about that. It seems that if we want to get real client IP, we need set provider(Hetzner) specific annotation on the LoadBalancer service.

# Preserving the client source IP

[docs](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)  
[tutorial](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer)

## Create and expose a small Nginx webserver that echoes back the client IP

```bash
$ k create deployment source-ip-app --image=registry.k8s.io/echoserver:1.4
$ k expose deployment source-ip-app --name=loadbalancer --port=80 --target-port=8080 --type=LoadBalancer

$ k get po -owide
NAME                             READY   STATUS    RESTARTS       AGE   IP             NODE
source-ip-app-5c687d697b-fppck   1/1     Running   1 (177m ago)   20h   10.244.1.172   roman-cluster-md-0-29vqt
$ k get svc loadbalancer -owide
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP                                  PORT(S)        AGE   SELECTOR
loadbalancer   LoadBalancer   10.103.111.206   10.0.0.6,2a01:4f9:c01d:433::1,65.109.42.56   80:31628/TCP   20h   app=source-ip-app
```

## Send a request to the LoadBalancer - `externalTrafficPolicy: Cluster`

Client address is `IP of the node` - because of SNAT:
```bash
$ curl 65.109.42.56
CLIENT VALUES:
client_address=65.109.204.179
...
$ k get node roman-cluster-md-0-29vqt -owide
NAME                       STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP
roman-cluster-md-0-29vqt   Ready    <none>   21h   v1.24.9   10.0.0.4      65.109.204.179
```

## Send a request to the LoadBalancer - `externalTrafficPolicy: Local`

Client address is `IP of the LoadBalancer` - there is no SNAT:
```bash
$ k patch svc loadbalancer -p '{"spec":{"externalTrafficPolicy":"Local"}}'
service/loadbalancer patched

$ curl 65.109.42.56
CLIENT VALUES:
client_address=65.109.42.56
...
```

## How to get "real" client IP regardless of externalTrafficPolicy

Use [proxy protocol](https://docs.hetzner.com/cloud/load-balancers/faq/) on the LoadBalancer:
```bash
# Hetzner CCM configures load balancer via annotations
$ k annotate svc loadbalancer 'load-balancer.hetzner.cloud/uses-proxyprotocol'=true
service/loadbalancer annotated
```

Nginx webserver needs to be modified to [accept proxy protocol](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/), otherwise we get *400 Bad Request*:
```bash
$ k exec -it source-ip-app-5c687d697b-fppck -- bash
root@source-ip-app-5c687d697b-fppck:/# cat /etc/nginx/nginx.conf
#...
http {
    #...
    server {
        # add the proxy_protocol parameter to the listen directive to accept proxy protocol
        # $proxy_protocol_addr now represents client IP
        listen 8080 default_server reuseport proxy_protocol;
        # you can change value of $remote_addr with RealIP module
        # 'http_realip_module' needs to be installed(not the case for this container)
        # specify IP address or the CIDR range of addresses of the TCP proxy or load balancer
        set_real_ip_from 65.109.204.179; # node IP in case of externalTrafficPolicy: Cluster
        #set_real_ip_from 65.109.42.56; # loadbalancer IP in case of externalTrafficPolicy: Local
        #set_real_ip_from 0.0.0.0/0; # if you don't know public IP
        #set_real_ip_from 10.0.0.0/16; # if your load balancer/node uses private IP
        # change IP with real_ip_header directive
        real_ip_header proxy_protocol;
        #...
    }
}
root@source-ip-app-5c687d697b-fppck:/# nginx -s reload
```

Client address is now "real" client IP:
```bash
$ curl 65.109.42.56
CLIENT VALUES:
client_address=<REAL_CLIENT_IP>
...
```

**Comment by garloff** [comment] 2023-01-18 20:40
Thanks, Roman!
On SCS clouds, the corresponding setting is an OpenStack-specific annotation:
 `loadbalancer.openstack.org/proxy-protocol: "true"`
and then patch the nginx charts to enable the proxy protocol.
We use kustomize as a robust method to patch yamls, see https://github.com/SovereignCloudStack/k8s-cluster-api-provider/tree/main/terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-proxy

One problem we ran into was issue https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/184:
When you access the service internally, the requests don't come from the LB and nginx then rejects due to missing proxy protocol. Do you observe the same on Hetzner?

**Comment by chess-knight** [comment] 2023-01-19 14:46
I observed the same on Hetzner. When the proxy protocol is turned on, I cannot access the service internally(e.g. from the pod).
So exactly the same behaviour, because the request doesn't go through the LB, so there is no proxy protocol at all.

I tried the workaround, which was mentioned by @flyersa [here](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/184#issue-1173549623).
Hetzner has a specific annotation `load-balancer.hetzner.cloud/hostname`, which causes the hostname to be populated to the *status.loadBalancer.ingress* of the loadbalancer service instead of LB IP.
After adding a hostname, I am able to access lb service internally.

This all happens because kube-proxy [adds an iptables rule](https://github.com/kubernetes/kubernetes/issues/66607) for the loadbalancer external IP, causing traffic to bypass the LB.
It seems that mentioned "workaround" is based on the behaviour of [AWS loadbalancer](https://github.com/kubernetes/kubernetes/issues/66607#issuecomment-474513060), which adds LB hostname instead of its IP
and therefore kube-proxy can't add it to the iptables and traffic goes through LB.

This behaviour was [fixed](https://github.com/kubernetes/kubernetes/pull/92312) in the upstream kubernetes project for the v1.20, but later it was [reverted](https://github.com/kubernetes/kubernetes/pull/96454).
There is now opened [issue](https://github.com/kubernetes/enhancements/issues/1860) which addresses the lb problem - milestone v1.28. The enhancement proposal is [KEP-1860](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1860-kube-proxy-IP-node-binding).

It seems that some providers adopt this *hostname* solution for this problem until the kubernetes project resolve that issue,
e.g. [DO](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/README.md#accessing-pods-over-a-managed-load-balancer-from-inside-the-cluster) or [linode](https://github.com/linode/linode-cloud-controller-manager/issues/74#issuecomment-721393082).
Also in almost all other providers, it is possible to set some kind of hostname annotation.

I also investigated [issue](https://github.com/kubernetes/cloud-provider-openstack/issues/1287) mentioned by @flyersa and
OpenStack Cloud Controller Manager is [no exception](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#use-proxy-protocol-to-preserve-client-ip). There is `loadbalancer.openstack.org/hostname` annotation, which can be used to explicitly set a hostname in the status of the load balancer service.
But there is also one unique option in the occm which I have not found anywhere else. It is called [`enable-ingress-hostname`](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#load-balancer).
It is used only when there is annotation `loadbalancer.openstack.org/proxy-protocol: "true"`. It adds dns suffix nip.io(it can be changed) to the load balancer IP address. So basically it creates hostname *IPaddress.nip.io*, returns it to the status of lb service and everything works.

I have found that it was adopted by [kops](https://github.com/kubernetes/kops/pull/12525) and [kubespray](https://github.com/kubernetes-sigs/kubespray/pull/7572). Probably there are other projects.
I have also found a problem with this setup in [external-dns](https://github.com/kubernetes/cloud-provider-openstack/pull/1449#issuecomment-818618929) project, but I don't know if it is fixed or whether it should interest us at all because we don't have external-dns in our stack.

Can we adopt this solution? We can probably set this occm setting when nginx-ingress is deployed as a load balancer with proxy protocol on. Then the service should be accessible externally as well as internally.

**Comment by garloff** [comment] 2023-01-23 09:26
The hostname approach will be further investigated and tested and looks like a valid option if it all works.

**Comment by chess-knight** [comment] 2023-01-30 08:35
During tests with Occm LoadBalancer setting [enable-ingress-hostname](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#load-balancer), I found one issue in 1.25 version.
When we install e.g. k8s version 1.25.4 we match occm version 1.25.3, but manifest which we curl from [occm repo](https://github.com/kubernetes/cloud-provider-openstack/blob/v1.25.3/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml) contains "only" images with tag 1.25.0.
Then when I tried to test the setting mentioned above, I hit a bug with occm 1.25.0. It was fixed in [1.25.2](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.25.2) but unfortunately, the image used in the manifest is 1.25.0 so the fix is not applied. So I created this [PR](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/322) which ensures the correct version is used in the manifest.

Apart from that problem, I tested it so it has the expected behaviour. I will do further tests and prepare PR.

**Comment by chess-knight** [comment] 2023-01-31 07:55
# Internal traffic doesn't work
Create a cluster with `NGINX_INGRESS_PROXY: true` in the [clusterctl.yaml](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/template/clusterctl.yaml.tmpl#L26):
```bash
$ k -n ingress-nginx get svc ingress-nginx-controller
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)
ingress-nginx-controller   LoadBalancer   10.109.235.18   213.131.230.192   80:31729/TCP,443:30709/TCP

$ k -n ingress-nginx describe svc ingress-nginx-controller
Annotations:              loadbalancer.openstack.org/enable-health-monitor: true
                          loadbalancer.openstack.org/load-balancer-id: 53a152f4-6c60-41e1-a954-51e985f40c1e
                          loadbalancer.openstack.org/proxy-protocol: true
External Traffic Policy:  Local
```

Create an example application and expose it via ingress:
```bash
k create deploy source-ip-app --image=registry.k8s.io/echoserver:1.4
k expose deploy source-ip-app --port=80 --target-port=8080
cat <<EOF | k apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: source-ip-app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: source-ip-app
            port:
              number: 80
EOF
```
```bash
$ k get deploy,svc,ing source-ip-app
NAME                            READY   UP-TO-DATE   AVAILABLE
deployment.apps/source-ip-app   1/1     1            1

NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)
service/source-ip-app   ClusterIP   10.102.165.90   <none>        80/TCP

NAME                                      CLASS   HOSTS   ADDRESS           PORTS
ingress.networking.k8s.io/source-ip-app   nginx   *       213.131.230.192   80
```

**Send a request to the load balancer IP:**
- external(from outside the cluster)
    ```bash
    $ curl 213.131.230.192
    ...
    HEADERS RECEIVED:
    accept=*/*
    host=213.131.230.192
    user-agent=curl/7.68.0
    x-forwarded-for=<REAL_CLIENT_IP>
    x-forwarded-host=213.131.230.192
    x-forwarded-port=80
    x-forwarded-proto=http
    x-forwarded-scheme=http
    x-real-ip=<REAL_CLIENT_IP>
    x-request-id=9351bbfe613235c4856b05581e178482
    x-scheme=http
    ```
- internal(from within the cluster)
    ```bash
    $ curl 213.131.230.192
    curl: (52) Empty reply from server
    $ wget 213.131.230.192
    Connecting to 213.131.230.192 (213.131.230.192:80)
    wget: error getting response
    ```
  It doesn't work from within the cluster.

# Internal traffic does work
Use same procedure as above but now set `enable-ingress-hostname=true` in the *[LoadBalancer]* section of [cloud.conf](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/template/cloud.conf.tmpl) and notice differences:
```bash
$ k -n ingress-nginx get svc ingress-nginx-controller
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP              PORT(S)
ingress-nginx-controller   LoadBalancer   10.109.235.18   213.131.230.192.nip.io   80:31729/TCP,443:30709/TCP

$ k get ing source-ip-app
NAME            CLASS   HOSTS   ADDRESS                  PORTS
source-ip-app   nginx   *       213.131.230.192.nip.io   80
```
The IP address is suffixed with [`nip.io`](https://nip.io/).

**Send a request to the load balancer IP:**
- external(from outside the cluster)
    ```bash
    $ curl 213.131.230.192
    ...
    HEADERS RECEIVED:
    accept=*/*
    host=213.131.230.192
    user-agent=curl/7.68.0
    x-forwarded-for=<REAL_CLIENT_IP>
    ...
    ```
- internal(from within the cluster)
    ```bash
    $ curl 213.131.230.192
    ...
    HEADERS RECEIVED:
    accept=*/*
    host=213.131.230.192
    user-agent=curl/7.47.0
    x-forwarded-for=213.131.230.90
    ...
    ```
  It works from within the cluster!

# Conclusion
I prepared this [PR](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/323) which adds `enable-ingress-hostname=true` to the occm config. This config option is [used](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/loadbalancer.go#L1822) only when the annotation `loadbalancer.openstack.org/proxy-protocol: "true"`, so for now, this setting is hardcoded, but after discussion, it can be set during the creation of cluster based on some variable.
After [research](https://github.com/SovereignCloudStack/issues/issues/250#issuecomment-1397089228) and tests, it seems to work as expected.
Also for k8s version 1.25 to work the [PR](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/322) has to be merged first as mentioned in this [comment](https://github.com/SovereignCloudStack/issues/issues/250#issuecomment-1408187653).

**Comment by jschoone** [comment] 2023-04-03 08:57
As discussed in container meeting CW14 the research has been done

**Closed** 2023-04-03 08:56 UTC
Labels: enhancement, Container, standardization, SCS-VP06c
