### ISSUE TITLE
Zuul node errors

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#517] opened 2024-01-11 08:18 UTC
We see that the Zuul runs into node errors every now and then.

![Screenshot 2024-01-09 at 22 01 38](https://github.com/SovereignCloudStack/issues/assets/51063/6c6fccb7-b366-41e0-8d2a-3be76e609280)

**Comment by okautz** [comment] 2024-01-30 16:33
Node failures that happend in the past could be categorized into two root causes:
1. Too many worker nodes were tried to be created, this hit the floating IP quota of the OpenStack Project. We amended the config to limit the creation of simultaneously created worker vms
2. Connection failure of the Zuul Executor to the Zookeeper after 3 retries. This is still about to be investigated with the zuul monitoring setup that is currently being implemented.

**Comment by okautz** [comment] 2024-06-18 14:07
Lately, NodeFailures occured again. It seems that Floating IPs were not cleared from the Zuul OpenStack project. After cleaning those up Nodes seem to become ready as intended again. I will look out for future issues for the next days

**Comment by okautz** [comment] 2024-11-29 13:46
As there is a new Zuul instance on https://zuul.sovereignit.cloud I'll close this.

**Closed as completed by okautz** 2024-11-29 13:46 UTC
Labels: Ops
